### ISSUE TITLE
system-addon filtering does not catch all system addons

### ISSUE THREAD

**Issue by mlopatka** [florian/taar-prototyping#3]
The strategy used here for filtering out system addons using the `WHERE NOT value.is_system` condition misses some of the Mozilla loaded fixes and side-loaded addons that behave like system addons.

TAAR modules use a different strategy for filtering system addons, see: https://github.com/mozilla/python_mozetl/blob/master/mozetl/taar/taar_locale.py#L43-L71

This means that the current estimation of module elegibility is not exactly true to the deployment of TAAR that is expected. Namely, addons such as 'firefox-hotfix@mozilla.org' and 'ubufox@ubuntu.com' are not filtered out.

This is not a huge issue, but is worth noting as it may lead to a systematic bias over-emphasizing the frequency with which collaborative-recommender is able to provide recommendations.

**Comment by Dexterp37** [comment]
We can easily prune these addons out using the AMO whitelist approach that's being used by the [jobs](https://github.com/mozilla/python_mozetl/blob/master/mozetl/taar/taar_utils.py#L56)

**Comment by mlopatka** [comment]
Issue still open, that was an accident :)

**Comment by mlopatka** [comment]
FIXED
